# Generated by Django 3.2.4 on 2023-09-25 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(default='', max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('book_category', models.CharField(choices=[('nonfiction', 'Non-Fiction'), ('fiction', 'Fiction'), ('historicalfiction', 'Historical Fiction'), ('romancenovel', 'Romance Novel'), ('horror', 'Horror'), ('sciencefiction', 'Science Fiction'), ('biography', 'Biography'), ('memoir', 'Memoir'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('childrensliterature', "Children's Literature"), ('humor', 'Humor'), ('selfhelp', 'Self-help'), ('yougadultfiction', 'Young Adult Fiction'), ('picturebook', 'Picture Book'), ('other', 'Other')], default='other', max_length=32)),
                ('review_body', models.TextField()),
                ('image', models.ImageField(blank=True, default='/review_placeholder_tceebf', upload_to='images/')),
                ('rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
