# Generated by Django 3.2.4 on 2023-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='/review_placeholder_tceebf.jpg', upload_to='images/'),
        ),
    ]
